utils::globalVariables(c(
  # Operador
  "%>%",
  # Variables internas (dot-prefixed)
  ".",
  ".cand_len",
  ".db_rank_key",
  ".dedup_key",
  ".Infra.Rank.upper",
  ".key",
  ".matched",
  ".matched_rank_upper",
  ".name_exact",
  ".input_name_clean",
  ".orig_len",
  ".row_id",
  ".status_rank",
  ".taxon_name_clean",
  ".rank_key",
  # Variables de columna / externas
  "direct_match_infra_rank",
  "fuzzy_infraspecies_dist",
  "fuzzy_match_infraspecies",
  "implied_infra",
  "Infra.Rank",
  "Infraspecies",
  "Input.Name",
  "is_sp",
  "is_spp",
  "Matched.Infraspecies",
  "matched_plant_name_id",
  "matched_taxon_name",
  "matched_taxon_authors",
  "n",
  "Orig.Infra.Rank",
  "Orig.Infraspecies",
  "Rank",
  "sorter",
  "Genus",
  "Matched.Genus",
  "Matched.Species",
  "Orig.Genus",
  "Orig.Species", "Species",
  "db_rank", "fuzzy_genus_dist", "fuzzy_species_dist",
  "taxon_name", "taxon_authors", "taxon_status",
  "accepted_plant_name_id", "accepted_taxon_name", "accepted_taxon_authors",
  "is_accepted_name",
  "genus",
  "infraspecies",
  "infraspecific_rank",
  "plant_name_id",
  "species",
  "Matched.Infra.Rank",
  "Orig.Name"
))
