utils::globalVariables(c(
  # Pipe operator
  "%>%",

  # Tidy-eval pronouns
  ".data",
  ".env",

  # Internal temporary variables (dot-prefixed)
  ".",
  ".cand_len",
  ".db_rank_key",
  ".dedup_key",
  ".Infra.Rank.upper",
  ".input_name_clean",
  ".key",
  ".matched",
  ".matched_rank_upper",
  ".name_exact",
  ".orig_len",
  ".rank_key",
  ".row_id",
  ".status_rank",
  ".taxon_name_clean",

  # Column names used across NSE pipelines
  "accepted_plant_name_id",
  "accepted_taxon_authors",
  "accepted_taxon_name",
  "db_rank",
  "direct_match_infra_rank",
  "fuzzy_genus_dist",
  "fuzzy_infraspecies_dist",
  "fuzzy_match_infraspecies",
  "fuzzy_species_dist",
  "Genus",
  "genus",
  "implied_infra",
  "Infra.Rank",
  "infraspecific_rank",
  "infraspecies",
  "Infraspecies",
  "Input.Name",
  "is_accepted_name",
  "is_sp",
  "is_spp",
  "Matched.Genus",
  "Matched.Infra.Rank",
  "Matched.Infraspecies",
  "Matched.Species",
  "matched_plant_name_id",
  "matched_taxon_authors",
  "matched_taxon_name",
  "n",
  "Orig.Genus",
  "Orig.Infra.Rank",
  "Orig.Infraspecies",
  "Orig.Name",
  "Orig.Species",
  "plant_name_id",
  "Rank",
  "sorter",
  "species",
  "Species",
  "taxon_authors",
  "taxon_name",
  "taxon_status",
  "direct_match",
  "direct_match_species_within_genus",
  "fuzzy_match_genus",
  "fuzzy_match_species_within_genus",
  "genus_match",
  "suffix_match_species_within_genus",
  ".taxon_key",
  "setNames", "genus_nchar",
  ".species_nchar", "Root"
))
