utils::globalVariables(c(
  # Operador
  "%>%",
  # Variables internas (dot-prefixed)
  ".",
  ".cand_len",
  ".db_rank_key",
  ".dedup_key",
  ".Infra.Rank.upper",
  ".key",
  ".matched",
  ".orig_len",
  ".rank_key",
  # Variables de columna / externas
  "direct_match_infra_rank",
  "fuzzy_infraspecies_dist",
  "fuzzy_match_infraspecies",
  "implied_infra",
  "Infra.Rank",
  "Infraspecies",
  "Input.Name",
  "is_sp",
  "is_spp",
  "Matched.Infraspecies",
  "n",
  "Orig.Infra.Rank",
  "Orig.Infraspecies",
  "Rank",
  "sorter",
  "Genus",
  "Matched.Genus",
  "Matched.Species",
  "Orig.Genus",
  "Orig.Species", "Species",
  "db_rank", "fuzzy_genus_dist", "fuzzy_species_dist",
  "genus",
  "infraspecies",
  "infraspecific_rank",
  "plant_name_id",
  "species"
))
